language: android
jdk: oraclejdk8
before_script:
    - "echo yes | android update sdk --no-ui --filter build-tools-24.0.3,android-24,extra-android-m2repository"
android:
  components:
    # The BuildTools version used by your project
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-24
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
