language: android
jdk: oraclejdk8
android:
  components:
    # The BuildTools version used by your project
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-24
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
