language: android
android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    # - build-tools-19.1.0

    # The SDK version used to compile your project
    # - android-24
